### ISSUE TITLE
Could you please add latest Spring Boot versions of these tutorials ? I purchase a book, but tutorials are old

### ISSUE THREAD

**Issue by javaHelper** [PacktPublishing/Mastering-Spring-Cloud#6]

**Comment by piomin** [comment]
This repository is related with the book, therefore changing versions of required libraries is not appropriate. If you are looking for some newest examples you can find it on my GitHub account https://github.com/piomin. I've got a copy of source examples on my account, where I'm trying to keep it up-to-date. For example:
https://github.com/piomin/sample-spring-cloud-consul
